lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # Path to your private key
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 604800 # Lebensdauer des Tokens in Sekunden (z.B. 7 Tage)

    # WICHTIG: Token Extractor Konfiguration
    token_extractors:
        authorization_header:
            enabled: false # Deaktivieren des Headers
        cookie:
            enabled: true # Aktivieren der Cookie-Extraktion
            name: BEARER # Der Name des Cookies, den wir im AuthController gesetzt haben
 
