security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        refresh:
            pattern: ^/api/token/refresh$
            stateless: true
            provider: app_user_provider
            refresh_jwt:
                check_path: /api/token/refresh

        main:
            # Firewall f端r deine Web-App + OAuth
            provider: app_user_provider
            custom_authenticators:
                - App\Security\GoogleAuthenticator
            lazy: true
            
            logout:
                path: app_logout
                # wohin nach logout
                target: app_home
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\JwtTokenAuthenticator

    access_control:
        - { path: ^/connect/google, roles: PUBLIC_ACCESS }
        - { path: ^/connect/google/check, roles: PUBLIC_ACCESS }
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api/login$, roles: PUBLIC_ACCESS }
        - { path: ^/api/register$, roles: PUBLIC_ACCESS }
    
        - { path: ^/api/password/request-reset$, roles: PUBLIC_ACCESS }
        - { path: ^/api/password/reset$, roles: PUBLIC_ACCESS }

        - { path: ^/api/agent, roles: PUBLIC_ACCESS }
        - { path: ^/api/index-knowledge, roles: PUBLIC_ACCESS }
        - { path: ^/api/devAgent, roles: PUBLIC_ACCESS }
        - { path: ^/api/frondend_devAgent, roles: PUBLIC_ACCESS }
        
        - { path: ^/api/token/refresh$, roles: PUBLIC_ACCESS }

        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4          # Minimal f端r bcrypt (schnellere Tests)
                time_cost: 3     # Minimal f端r argon2
                memory_cost: 10  # Minimal f端r argon2