security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        refresh:
            pattern: ^/api/token/refresh$
            stateless: true
            provider: app_user_provider
            refresh_jwt:
                check_path: /api/token/refresh
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\JwtTokenAuthenticator
                - App\Security\GoogleAuthenticator
        
        

    access_control:
        - { path: ^/api, roles: PUBLIC_ACCESS, methods: [OPTIONS] }
        - { path: ^/api/connect/google, roles: PUBLIC_ACCESS }
        - { path: ^/api/connect/google/check, roles: PUBLIC_ACCESS }
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api/login$, roles: PUBLIC_ACCESS }
        - { path: ^/api/register$, roles: PUBLIC_ACCESS }
        
        - { path: ^/api/password/request-reset$, roles: PUBLIC_ACCESS }
        - { path: ^/api/password/reset$, roles: PUBLIC_ACCESS }

        - { path: ^/api/agent, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/index-knowledge, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/devAgent, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/frondend_devAgent, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/token/refresh$, roles: IS_AUTHENTICATED_FULLY }

        


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4          # Minimal für bcrypt (schnellere Tests)
                time_cost: 3     # Minimal für argon2
                memory_cost: 10  # Minimal für argon2