controllers:
    resource: ../src/Controller/
    type: attribute
login:
    path: /api/login
    methods: [POST]
api_refresh_token:
    path: /api/token/refresh
connect_google:
  path: /api/connect/google
  controller: App\Controller\GoogleController::connect

